/**
 * Generate the .env file content for the MCP server.
 */
export function generateEnvContent({
  serverUrl = 'https://x402-api.onrender.com',
  maxBudget = '1.00',
  network = 'mainnet',
  agentPrivateKey = '',
  coinbaseApiKey = '',
  coinbaseApiSecret = '',
}) {
  let content = `# x402 Bazaar MCP Server Configuration
# Generated by: npx x402-bazaar init

# Marketplace server URL
X402_SERVER_URL=${serverUrl}

# Maximum USDC budget per session (safety limit)
MAX_BUDGET_USDC=${maxBudget}

# Network: mainnet or testnet
NETWORK=${network}
`;

  if (agentPrivateKey) {
    content += `
# Agent wallet private key (Ethereum)
# WARNING: Keep this secret! Never commit to git.
AGENT_PRIVATE_KEY=${agentPrivateKey}
`;
  }

  // Polygon facilitator env vars (gas-free payments via PIP-82)
  if (network === 'polygon') {
    content += `
# Polygon x402 Facilitator (gas-free payments via PIP-82)
POLYGON_FACILITATOR_URL=https://x402.polygon.technology
POLYGON_FEE_SPLITTER_CONTRACT=0x820d4b07D09e5E07598464E6E36cB12561e0Ba56
`;
  }

  if (!agentPrivateKey && coinbaseApiKey) {
    content += `
# Coinbase Developer Platform API credentials (legacy mode)
# Get yours at: https://portal.cdp.coinbase.com/
COINBASE_API_KEY=${coinbaseApiKey}
COINBASE_API_SECRET=${coinbaseApiSecret}
`;
  }

  return content;
}
