/**
 * Generate the .env file content for the MCP server.
 */
export function generateEnvContent({
  serverUrl = 'https://x402-api.onrender.com',
  maxBudget = '1.00',
  network = 'mainnet',
  coinbaseApiKey = '',
  coinbaseApiSecret = '',
  seedPath = 'agent-seed.json',
}) {
  return `# x402 Bazaar MCP Server Configuration
# Generated by: npx x402-bazaar init

# Marketplace server URL
X402_SERVER_URL=${serverUrl}

# Maximum USDC budget per session (safety limit)
MAX_BUDGET_USDC=${maxBudget}

# Network: mainnet or testnet
NETWORK=${network}

# Coinbase Developer Platform API credentials
# Get yours at: https://portal.cdp.coinbase.com/
COINBASE_API_KEY=${coinbaseApiKey}
COINBASE_API_SECRET=${coinbaseApiSecret}

# Path to the agent wallet seed file
AGENT_SEED_PATH=${seedPath}
`;
}
